version: "2"

run: # параметры запуска линтера
  timeout: 5m # максимальное время выполнения анализа
  relative-path-mode: gomod # пути к файлам интерпретируется относительно корня go-модуля
  issues-exit-code: 1 # код выхода = 1, если найдены ошибки (полезно для CLI)
  tests: true # анализировать также тесты
  modules-download-mode: readonly # не разрешать загрузку зависимостей во время анализа (безопасно и быстрее в CI)

output: # настройка вывода линтеров
  formats:
    text: # формат вывода в терминале
      print-linter-name: true # показывать имя линтера рядом с каждым сообщением
      print-issued-lines: true # показывать строку кода, где найдена проблема
      colors: true # использовать цветной вывод (для улучшения читаемости)

issues: # общие настройки для обработки проблем
  max-issues-per-linter: 0 # без лимита на количество ошибок от одного линтера
  max-same-issues: 0 # без лимита на количество одинаковых ошибок
  uniq-by-line: true # отображать максимум одну ошибку на строку (избекает спама от разныхх линтеров на по одной строке)

linters: # список активныхх и отключенных линтеров
  default: standard # использовать стандартный набор линтеров golangci-lint
  enable: # явно включенные линтеры
    - errcheck # проверяет, что ошибки не ингнорируются
    - staticcheck # глубойки статический анализ. (inclides gosimple, stylecheck)
    - govet # встроенный в Go инструмент анализа (ловит потенциальные баги)
    - gocritic # набор продвинутых правил для улучшения качества кода
    - revive # проверяет стиль кода, оформление, название
    - unused # проверяет неиспользуемые переменные, типы и функции
    - gosec # проверяет на уязвимости и небезопасные практики
    - depguard # запрещает импорт указанных пакетов (контроль зависимостей)
    - bodyclose # проверяет что закрывается тело у http запросов
    - asciicheck # предупреждает о не ASCII символах в коде
    - cyclop # проверяет цикломатическую сложность функций
    - dupl # проверяет диблированные фрагменты кода
    - ineffassign # обнаруживает неиспользованиное присваивание
    - unparam # находит неиспользуемые параметры функции
    - errorname # проверяет имена переменных/типов ошибок (должны содержать "Err")
    - forbidigo # запрещает определённые вызовы или конструкции по regexp-паттернам
    - contextcheck # проверяет что context.Context передаётся в методы/функции
    - conteinedctx # предупреждает, если context.Context сохраняется в структуре (плохо)
  disable: # линтеры, которые намеренно отключены
    - gocyclo # старый линтер сложности (заменён на cyclop)
    - lll # проверка длинны строк (часто шумная и мешает)

  exclusions: # исключения из анализа
    generated: strict # игнорировать сгенерированные файлы (по "// Code generated ... DO NOT EDIT.")
    rules: # локальные исключения по пути/файлу/линтерам
      - path: _test\.go # для всех тестов:
        linters:
          - cyclop # не проверять сложность тестов
          - dupl # не проверять дубликацию в тестах
          - gosec # не искать уязвимости в тестах

  settings: # индивидуальные настройки для конкретных линтеров
    gosec:
      # включаем все правила, включая экспериментальные
      config: # исключить проверку в указанных директориях
        globals:
          audit: true #  активировать все правила безопасности
          show-ignored: true # показывать проигнорированные проблемы в комментариях
        severity: medium # минимальная важность проблем, high/medium/low
        confidence: medium # минимальная уровень уверенности high/medium/low

    cyclop:
      max-complexity: 20 # допустимая сложность функций (больше 10, но не слишком жестоко)

    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil # запретить использовать устаревший пакет
              desc: Использование устаревшего пакета io/ioutil запрещено (замените вызовы на налоги)

    revive:
      severity: warning # нарушение revive будут как предупреждения, а не ошибки

    forbidigo:
      exclude-godoc-examples: true # не применять запреты к godoc примерам
      analyze-types: true # искать запреты и в типах/константах, а не только в функциях
      forbid: # Список запрещённых паттернов
        - pattern: ^fmt\.Print.*$ # Запрет использования fmt.Print* и т.д.
          msg: Запрещено напрямую использовать, вместо этого используйте логгер
        - pattern: ^time.Sleep$ # Запрет использования time.Sleep
          msg: Запрещено напрямую использования time.Sleep (вместо этого используйте context.WithTimeout или context.WithDeadline)
        - pattern: ^http\.DefaultClient$ # Запрет использования http.DefaultClient
          msg: Не используйте http.DefaultClient (нет таймаутов), создайте *http.Client с таймаутом

formatters: # Форматтеры кода (проверка стиля кода)
  enable:
    - gofumpt # строгая версия go-fmt с дополтинельными правилами
    - gci # форматтер импортов (гибкая альтернатива goimports)
  settings:
    gofumpt:
      extra-rules: true # включить дополнительные строгие правил (например, удаление лишних пустых строк)
    gci:
      sections:
        - standard
        - default
        - Prefix (github.com/AndreyTsegelnikov/go-microservice) # локальные импорты
      no-inline-comments: false # разрешить комментарии после импортов